# Use a imagem oficial do Node
FROM node:20-alpine as builder

WORKDIR /app

COPY package*.json ./

# Instala dependências
RUN npm install

# Copia os arquivos do projeto
COPY . .

RUN npm i -g pnpm
    
EXPOSE 3000

# Comando de execução do servidor Next.js
CMD ["node", "server.js"]