# Use a imagem oficial do Node como base
FROM node:20-alpine 

# Define o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copia package.json e package-lock.json (ou yarn.lock)
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código da aplicação
COPY . .

# Expõe a porta que o seu servidor Node/Express está rodando (ex: 3001)
EXPOSE 3030

# Comando para iniciar a aplicação
CMD [ "npm", "start" ]